Game logic: Milestone 3
Stricks1/TicTacToe pull request #3
Opened 2020-05-13 17:11 UTC by rindrajosia

In this branch we:
Add real logic for your game.
main.rb file is responsible for user interaction

2020-05-14 01:17 UTC, serdg0 requested changes
Hi @rindrajosia & @Stricks1 !
Very good job! Overall, this project is awesome! You are **VERY** close to finish it! :racing_car: :racing_car: 

We only require to change some minor issues in order to get your project approved:

- [ ]  Classes should be in the lib folder.

- [ ] There is 1 inline comment.

- [ ] The draw message is always being printed.

After adressing those minor bugs submit anoter CRR.

**Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_** (edited)

2020-05-15 09:44 UTC, suretrust requested changes
Hi @rindrajosia, 👋 

### Great job implementing the suggested changes. 🙌 However, I couldn't run your app. 👇 

- [ ] See my comments on your code to locate the bug.

<img width="1169" alt="Screenshot 2020-05-15 at 10 39 15" src="https://user-images.githubusercontent.com/31304943/82036518-e5092a80-9698-11ea-9145-dbbc9eb378bf.png">

**Kindly submit for another CRR once these issues have been fixed.** _Happy coding!_ 🎉

2020-05-15 09:44 UTC, suretrust commented on bin/main
> +require '../lib/playagain.rb'
Use `require_relative` for files within the folder structure. Require should be used for external files, like gems, while require_relative should be used for referring to files within your directory.

2020-05-16 02:54 UTC, rOluochKe requested changes
Hello Team!
### You have a conflict in the main.rb file, solve and submit for another code review. Good luck.
![conflict](https://user-images.githubusercontent.com/8114528/82108780-b8f1b600-9739-11ea-9b11-88d07dd980c7.png)

2020-05-16 05:40 UTC, rindrajosia commented
> Hello Team!
> ### You have a conflict in the main.rb file, solve and submit for another code review. Good luck.
> 
> ![conflict](https://user-images.githubusercontent.com/8114528/82108780-b8f1b600-9739-11ea-9b11-88d07dd980c7.png)

Hello 
thanks for the review however we don't face this merge conflict in our computeur.
Anyway, we have updated our main.rb to try to resolve this merge conflict even if we don't see it when we make a pull request.
![conflict](https://user-images.githubusercontent.com/58552748/82111888-c1a1b680-9750-11ea-8ccf-b88dcf00a239.png)

2020-05-17 17:06 UTC, pelzolga123 approved these changes
Approved.

2020-05-17 17:07 UTC, pelzolga123 commented
## Hi Team,
### Good work, you did everything required previously :+1:  Approved.
Just before you merge this project consider a few more changes:
* Why do you need a separate file for the `play_again` method? Please move this method to `main` file and delete `playagain.rb` file.
* Add a validation that will not allow the player to have a blank name.

Then go ahead and merge into development.
_Goodluck in your next milestone_ *Happy coding*

2020-05-18 19:50 UTC, merged